# Generated by Django 3.2.2 on 2022-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='접속 IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='인증번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('선택안함', '선택안함'), ('일반 가입자', '일반 가입자'), ('서비스 가입자', '서비스 가입자')], max_length=24, null=True, verbose_name='서비스 사용자'),
        ),
    ]
