# Generated by Django 3.2.2 on 2023-01-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221107_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='핸드폰번호'),
        ),
    ]
