# Generated by Django 3.2 on 2023-02-11 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, unique=True, verbose_name='지역')),
                ('site', models.CharField(max_length=100, unique=True, verbose_name='현장 위치')),
                ('sitenickname', models.CharField(default='', max_length=100, unique=True, verbose_name='별칭')),
            ],
            options={
                'verbose_name': '설치 현장',
                'verbose_name_plural': '설치 현장',
                'db_table': 'installationsite',
            },
        ),
        migrations.CreateModel(
            name='topicManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintopic', models.CharField(max_length=50, unique=True, verbose_name='메인 토픽')),
                ('subtopic', models.CharField(max_length=50, unique=True, verbose_name='서브 토픽')),
                ('topicnicname', models.CharField(default='', max_length=100, unique=True, verbose_name='별칭')),
            ],
            options={
                'verbose_name': '토픽 종합 관리',
                'verbose_name_plural': '토픽 종합 관리',
                'db_table': 'topicmanage',
            },
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverip', models.CharField(max_length=50, verbose_name='MQTT 접속 IP')),
                ('serverport', models.CharField(max_length=50, verbose_name='MQTT 접속 Port')),
                ('installationsite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.installationsite', verbose_name='현장 선택')),
                ('topic', models.ManyToManyField(to='control.topicManage', verbose_name='토픽')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '회원별 토픽 관리',
                'verbose_name_plural': '회원별 토픽 관리',
                'db_table': 'manage',
            },
        ),
    ]
