# Generated by Django 3.2 on 2023-02-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage',
            name='managenicname',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='별칭'),
        ),
    ]
