# Generated by Django 3.2 on 2023-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_manage_managenicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmanage',
            name='maintopic',
            field=models.CharField(max_length=50, verbose_name='메인 토픽'),
        ),
    ]
